config/routes.rb
Rails.application.routes.draw do
  resources :invites, controller: 'invites', only: [:new, :create]
  devise_for :users
  root 'static_pages#index'

  get "/trips", to: 'static_pages#index'
  get "/aboutus", to: 'static_pages#index'
  get "/hotels", to: 'static_pages#index'
  get "/tripflights", to: 'static_pages#index'
  get "/trips/new", to: 'static_pages#index'
  get "/trips/:id", to: 'static_pages#index'
  get "/trips/:id/events", to: 'static_pages#index'
  get "/trips/:id/events/new", to: 'static_pages#index'
  get "events/:id/edit", to: 'static_pages#index'
  get "/trips/:id/flights/new", to: 'static_pages#index'
  get "/trips/:id/flights", to: 'static_pages#index'
  get "/trips/:trip_id/events", to: 'static_pages#index'
  get "/trips/:trip_id/events/:id", to: 'static_pages#index'
  get "invites/new", to: 'static_pages#index'
  get "reviews", to: 'static_pages#index'
  get "/chatroom", to: 'static_pages#index'

  namespace :api do
    namespace :v1 do
      resources :trips, only: [:index, :show, :create, :update] do
        resources :events, only: [:index,:show, :create, :update]
        resources :chats, only: [:index, :new, :create]
      end
      resources :chats, only: [:index,:new,:create]
      resources :hotels, only: [:index, :new, :create, :update]
      resources :users, only: [:index, :new, :create]
      resources :flights, only: [:index, :new, :create]
      resources :invites, only: [:index, :new, :create]
      resources :reviews, only: [:index, :new, :create]
    end
  end

  resources :users, only: [:index, :new, :create]

  as :user do
    get 'signup' => 'devise/sessions#new'
    post 'signin' => 'devise/sessions#create'
    delete 'signout' => 'devise/sessions#destroy'
  end

end

app/views/layouts/application.html.erb
<link href="https://fonts.googleapis.com/css2?family=Francois+One&display=swap" rel="stylesheet">

<!DOCTYPE html>
<html>
<head>
  <title>FriendTrip</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('FTLOGO.png') %>
  <script src="https://api.mqcdn.com/sdk/mapquest-gl-js/v0.4.0/mapquest-gl.js"></script>
<link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/mapquest-gl-js/v0.4.0/mapquest-gl.css"/>
</head>
<body>
  <nav>
    <div class="top-bar nav-white white-back">
      <a href="/" class="friendtrip-logo left vert"><%= image_tag "new-logo.png"%></a>
        <%- if current_user -%>
        <div class="topnav center" id="myTopnav">
          <a><%= link_to 'MY FRIENDTRIPS', trips_path %></a>
          <a><%= link_to 'ABOUT US', aboutus_path %></a>
          <a><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %></a>
        </div>
        <%- else -%>
        <div class="topnav" id="myTopnav">
          <a><%= link_to 'SIGN UP', new_user_registration_path %></a>
          <a><%= link_to 'SIGN IN', new_user_session_path %></a>
        </div>
        <%- end -%>



    </div>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>

  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_API_KEY"]}&libraries=places" %>
  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
  </body>
</html>